In [1]:
import numpy as np

In [2]:
data1 = [3.5, 5, 6, 2] # list
arr1 = np.array(data1) # array1

In [3]:
arr1

array([3.5, 5. , 6. , 2. ])

In [4]:
data2 = (4, 5, 3.2, 7) # tuple
arr2 = np.array(data2)

In [5]:
arr2

array([4. , 5. , 3.2, 7. ])

In [6]:
arr1.ndim

1

In [7]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]] # list ichidagi list (nested list)
arr3 = np.array(data3) # array3

In [8]:
arr3.shape # qator va ustunlar sonini ko'rsatadi (q, u)

(2, 4)

In [9]:
arr3.size # array3 ning elementlar soni 

8

In [10]:
arr4 = np.zeros((2, 4)) # barcha elemtlari 0 ga teng bo'lgan (2, 4)
arr4 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
arr7 = np.arange(20) # 0 dan 20 gacha bo'lgan qiymatlarni 1 qadam bilan massivga joylab beradi
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
arr8 = np.random.rand(2, 4) # (2, 4) o'lchamli --> elementlar (0 ~ 1) taxminiy qiymatlardan tashkil topgan
arr8

array([[0.61349256, 0.01004047, 0.75289892, 0.04922295],
       [0.7661152 , 0.48984731, 0.85198268, 0.92009251]])

In [13]:
arr9 = np.random.randint(5, size=(2, 4)) # (2, 4) o'lchamli va max qiymati 5 gacha bo'lgan int sonlar
arr9

array([[3, 1, 3, 1],
       [0, 4, 3, 4]])

In [14]:
arr10 = np.random.randn(2, 4) # (2, 4) o'lchamli --> elementlari (Normal dist)
arr10 

array([[-2.44424776,  0.04218688,  0.2539772 , -0.52653476],
       [-0.27566847,  0.8709075 ,  1.2846298 , -1.50704192]])