In [1]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3], dtype=np.float32) # -> 32 bitli float type
arr1

array([1., 2., 3.], dtype=float32)

In [4]:
arr2 = np.array([1, 2, 3], dtype=np.int)
arr2 

array([1, 2, 3])

In [7]:
# check dtype
arr1.dtype

dtype('float32')

In [9]:
arr2.dtype

dtype('int64')

In [12]:
arr = np.array([1, 2, 3, 4]) # default int64
arr.dtype

dtype('int64')

In [16]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4.])

In [17]:
float_arr.dtype

dtype('float64')