![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. 
## 2.1. NumPy kutubxonasi bilan ishlash

### NumPy kutubxonasini chaqirib olish

In [ ]:
import numpy as np

### 2.1.1. N-o'lchamli massiv (array)larga ishlov berish

### Bolean Indekslash

In [ ]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [ ]:
# data
data = np.random.randn(7, 4)
data

array([[-0.53188163, -0.10705259, -0.20993863,  1.8967824 ],
       [ 0.60283261, -0.14034977, -0.0923303 ,  0.37854178],
       [ 0.07191395,  1.07229759,  0.10236782,  0.6537079 ],
       [-1.2909134 , -0.57715948,  0.00242281,  0.96883777],
       [ 0.97125202, -0.03558379, -0.16035862, -0.90338805],
       [ 0.25626888,  1.75120741, -1.10553012,  0.88876279],
       [-0.51654642,  1.17040117,  1.27444859, -0.33890306]])

In [ ]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [ ]:
data[names == 'Hasan'] # Hasanga tegishli barcha ma'lumotlarni ajratib olish

array([[-0.53188163, -0.10705259, -0.20993863,  1.8967824 ],
       [ 0.97125202, -0.03558379, -0.16035862, -0.90338805]])

In [ ]:
data[names == 'Elyor'] # Elyorga tegishli barcha ma'lumotlarni ajratib olish

array([[-1.2909134 , -0.57715948,  0.00242281,  0.96883777],
       [-0.51654642,  1.17040117,  1.27444859, -0.33890306]])

In [ ]:
data[names=='Hasan', 2:] # Hasanga tegishli oxirgi ikkita ustundagi ma'lumotlarni ajratib olish

array([[-0.20993863,  1.8967824 ],
       [-0.16035862, -0.90338805]])

In [ ]:
data[names != 'Hasan'] # (!=)Hasandan tashqari barcha insonlarning ma'lumotlarni ajratib olish

array([[ 0.60283261, -0.14034977, -0.0923303 ,  0.37854178],
       [ 0.07191395,  1.07229759,  0.10236782,  0.6537079 ],
       [-1.2909134 , -0.57715948,  0.00242281,  0.96883777],
       [ 0.25626888,  1.75120741, -1.10553012,  0.88876279],
       [-0.51654642,  1.17040117,  1.27444859, -0.33890306]])

In [ ]:
data[~(names == 'Hasan')] # (~) yuqoridagi cell bilan bir xil natijani berar ekan

array([[ 0.60283261, -0.14034977, -0.0923303 ,  0.37854178],
       [ 0.07191395,  1.07229759,  0.10236782,  0.6537079 ],
       [-1.2909134 , -0.57715948,  0.00242281,  0.96883777],
       [ 0.25626888,  1.75120741, -1.10553012,  0.88876279],
       [-0.51654642,  1.17040117,  1.27444859, -0.33890306]])

In [ ]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[-0.53188163 -0.10705259 -0.20993863  1.8967824 ]
 [ 0.60283261 -0.14034977 -0.0923303   0.37854178]
 [ 0.07191395  1.07229759  0.10236782  0.6537079 ]
 [-1.2909134  -0.57715948  0.00242281  0.96883777]
 [ 0.97125202 -0.03558379 -0.16035862 -0.90338805]
 [ 0.25626888  1.75120741 -1.10553012  0.88876279]
 [-0.51654642  1.17040117  1.27444859 -0.33890306]]


In [ ]:
mask = (names == 'Hasan') | (names == 'Husan') # "|" or (yoki)
mask

array([ True,  True, False, False,  True, False, False])

In [ ]:
data[mask] # Hasan va Husanlarga tegishli ma'lumotlarni ajratib olish

array([[-0.53188163, -0.10705259, -0.20993863,  1.8967824 ],
       [ 0.60283261, -0.14034977, -0.0923303 ,  0.37854178],
       [ 0.97125202, -0.03558379, -0.16035862, -0.90338805]])

In [ ]:
data

array([[-0.53188163, -0.10705259, -0.20993863,  1.8967824 ],
       [ 0.60283261, -0.14034977, -0.0923303 ,  0.37854178],
       [ 0.07191395,  1.07229759,  0.10236782,  0.6537079 ],
       [-1.2909134 , -0.57715948,  0.00242281,  0.96883777],
       [ 0.97125202, -0.03558379, -0.16035862, -0.90338805],
       [ 0.25626888,  1.75120741, -1.10553012,  0.88876279],
       [-0.51654642,  1.17040117,  1.27444859, -0.33890306]])

In [ ]:
data[data<0] = 0
data

array([[0.        , 0.        , 0.        , 1.8967824 ],
       [0.60283261, 0.        , 0.        , 0.37854178],
       [0.07191395, 1.07229759, 0.10236782, 0.6537079 ],
       [0.        , 0.        , 0.00242281, 0.96883777],
       [0.97125202, 0.        , 0.        , 0.        ],
       [0.25626888, 1.75120741, 0.        , 0.88876279],
       [0.        , 1.17040117, 1.27444859, 0.        ]])