In [1]:
import numpy as np

In [2]:
arr = np.arange(10, 100, 10)

In [3]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
arr[-2]

80

In [5]:
arr[3:5]

array([40, 50])

In [8]:
sliced_arr = arr[3:5]
sliced_arr = 0

In [9]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
sliced_arr

0