In [ ]:
# Best practice, use an environment rather than install in the base env
conda create -n my-env
conda activate my-env
# If you want to install from conda-forge
conda config --env --add channels conda-forge
# The actual install command
conda install numpy

In [ ]:
## install numpy
# use conda
!conda install numpy
# use pip
!pip install numpy

In [ ]:
# How to import NumPy
import numpy as np

In [ ]:
# simple array 
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
# 2D array simple
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
# shape
a2.shape

(1, 6)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0]

array([1, 2, 3, 4])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(2)


array([1., 1.])

In [ ]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(2, 9, 2)


array([2, 4, 6, 8])

In [ ]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])